= Community

The Fedora Container SIG mission is to maintain, grow, guide and promote best practice of the development and release of container images.

Container images built and released by the Fedora Project are available on our https://registry.fedoraproject.org[registry]


== Joining and participating in the Container SIG

We don't have a formalized join process. Signing up on the mailing list, coming to Container SIG meetings, and joining our IRC channel are good ways to get involved.

== Communication

https://discussion.fedoraproject.org/c/server/containers[Forum]

https://lists.fedoraproject.org/archives/list/container-sig@lists.fedorahosted.org/[mailing list]

Fedora Container folks hang out on irc.freenode.net at #fedora-containers

Haven't used IRC for communication before? More information on how to use IRC is available https://fedoraproject.org/wiki/IRC[here].

https://pagure.io/ContainerSIG/container-sig[Issue tracker]


== Meetings

The SIG does not have regular meeting, we prefer async communication via the mailing list or the forum. We are organizing Virtual Fedora Activity Day (VFAD) when needed to meet and focus on specific topics if needed.
